DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE REVIEW;
DROP TABLE REPLY;
DROP TABLE REPLY_RE;
DROP TABLE FAV;
DROP TABLE NOVEL;
DROP TABLE LLIKE;
DROP TABLE OPINION;



SELECT * FROM BOARD;
SELECT * FROM MEMBER;
SELECT * FROM USER_TABLES;
SELECT * FROM NOVEL;

CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   MNAME VARCHAR(20) NOT NULL,
   NICKNAME VARCHAR(20) NOT NULL,
   MPHONE VARCHAR(20) NOT NULL,
   MEMAIL VARCHAR(50) NOT NULL,
   ROLE VARCHAR(20) NOT NULL
)


CREATE TABLE OPINION(
   OID INT PRIMARY KEY,
   NID INT NOT NULL,
   OCONTENT VARCHAR(500) NOT NULL,
   ODATE  DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   OSTAR INT NOT NULL
);

CREATE TABLE BOARD(
   BID INT PRIMARY KEY,
   BTITLE VARCHAR(50) NOT NULL,
   BCONTENT VARCHAR(1000) NOT NULL,
   BDATE DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   LID INT NOT NULL
);



CREATE TABLE REPLY(
   RID INT PRIMARY KEY,
   RCONTENT VARCHAR(1000) NOT NULL,
   RDATE DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   BID INT NOT NULL,
   CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);


CREATE TABLE REPLY_RE(
   RRID INT PRIMARY KEY,
   RRCONTENT VARCHAR(1000) NOT NULL,
   RRDATE  DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   BID INT NOT NULL,
   RID INT NOT NULL,
   CONSTRAINT REPLY_REPLY_RE FOREIGN KEY (RID) REFERENCES REPLY(RID) ON DELETE CASCADE
);


CREATE TABLE NOVEL(
   NID INT PRIMARY KEY,
   NTITLE VARCHAR(70) NOT NULL,
   NCONTENT VARCHAR(1000) NOT NULL,
   NIMG VARCHAR(2000) NOT NULL,
   NGENRE VARCHAR(60) NOT NULL,
   NWRITER VARCHAR(30) NOT NULL,
);


CREATE TABLE LLIKE(
   LID INT PRIMARY KEY,
   MID VARCHAR(20) NOT NULL,
   BID INT NOT NULL,
   LSTATUS INT DEFAULT 0,
   NLSTATUS INT DEFAULT 0,
   REPORT INT DEFAULT 0,
   CONSTRAINT BOARD_LLIKE FOREIGN KEY (BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);



