CREATE TABLE MEMBER(
	MID VARCHAR(10) PRIMARY KEY,
	MPW VARCHAR(10) NOT NULL,
	MNAME VARCHAR(20) NOT NULL,
	MPK INT NOT NULL
);
CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL, -- FK는 반드시 상대 테이블의 PK를 사용
	MSG VARCHAR(50) NOT NULL,
	FAVCNT INT DEFAULT 0,
	RCNT INT DEFAULT 0
);

CREATE TABLE REPLY(
	RID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL,
	BID INT NOT NULL,
	RMSG VARCHAR(30) NOT NULL,
	CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD (BID) ON DELETE CASCADE
);

CREATE TABLE FAV(
	FID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL,
	BID INT,
	FAV INT DEFAULT 1,
	CONSTRAINT BOARD_FAV FOREIGN KEY (BID) REFERENCES BOARD (BID) ON DELETE CASCADE
);

INSERT INTO FAV(FID,MID,BID) VALUES((SELECT NVL(MAX(FID),0)+1 FROM FAV),?,?)

SELECT * FROM USER_TABLES;

SELECT * FROM BOARD;
SELECT * FROM REPLY;
SELECT * FROM MEMBER;
SELECT * FROM FAV;

DROP TABLE MEMBER;

SELECT * FROM BOARD WHERE MID='ari' ORDER BY BID DESC;

SELECT * FROM (SELECT * FROM MEMBER ORDER BY ROWNUM DESC) WHERE ROWNUM <=3;



